FROM ghcr.io/cargo-prebuilt/cross-auditable:armv7-unknown-linux-gnueabihf

RUN dpkg --add-architecture armhf
RUN apt update && apt upgrade -y \
    && apt install -y libssl-dev:armhf \
    && rm -rf /var/lib/apt/lists/*
