FROM ghcr.io/cargo-prebuilt/cross-auditable:x86_64-unknown-linux-gnu

RUN dpkg --add-architecture amd64
RUN apt update && apt upgrade -y \
    && apt install -y libssl-dev:amd64
    && rm -rf /var/lib/apt/lists/*
