FROM ghcr.io/cargo-prebuilt/cross-auditable:aarch64-unknown-linux-gnu

RUN dpkg --add-architecture arm64
RUN apt update && apt upgrade -y \
    && apt install -y libssl-dev:arm64 \
    && rm -rf /var/lib/apt/lists/*
