ARG TARGET
FROM ghcr.io/cargo-prebuilt/cross-auditable:$TARGET as builder
ARG BUILD_COMBO

RUN apt update && apt upgrade -y \
    && apt install -y checkinstall \
    && rm -rf /var/lib/apt/lists/*

COPY openssl /

WORKDIR /openssl

RUN ./Configure $BUILD_COMBO --cross-compile-prefix=$CROSS_TOOLCHAIN_PREFIX --prefix=/usr/local/ssl --openssldir=/usr/local/ssl
RUN make
RUN checkinstall

RUN ls

FROM ghcr.io/cargo-prebuilt/cross-auditable:$TARGET

RUN apt update && apt upgrade -y \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /openssl /openssl
