FROM ghcr.io/cargo-prebuilt/cross-auditable:riscv64gc-unknown-linux-gnu

RUN dpkg --add-architecture riscv64
RUN apt update && apt upgrade -y \
    && apt install -y libssl-dev:riscv64
    && rm -rf /var/lib/apt/lists/*
